# Generated by Django 3.0.6 on 2020-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArchiSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default=None, upload_to='images/portfolio1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default=None, upload_to='images/portfolio2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default=None, upload_to='images/portfolio3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(default=None, upload_to='images/portfolio4'),
        ),
    ]
