# Generated by Django 3.0.8 on 2020-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArchiSite', '0002_auto_20200619_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplans',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
