# Generated by Django 3.1.3 on 2021-03-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArchiSite', '0004_auto_20200720_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousePlans',
        ),
    ]
